matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10.15.1"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: generic

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      ./scripts/add-osx-cert.sh
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo rm /usr/local/bin/docker-compose
      curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
      chmod +x docker-compose
      sudo mv docker-compose /usr/local/bin
    fi

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      make release-win-linux-ci
    else
      yarn release
    fi

after_script:
  - make clean

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
